// frontend/src/pages/Login.jsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Card, Form, Input, Button, Typography, Alert, Space } from 'antd'
import { CloudServerOutlined, MailOutlined, LockOutlined } from '@ant-design/icons'
import { motion } from 'framer-motion'
import useAuthStore from '../store/authStore'

const { Title, Text, Paragraph } = Typography

export default function Login() {
  const navigate = useNavigate()
  const login = useAuthStore((s) => s.login)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const onFinish = async (values) => {
    setLoading(true)
    setError('')
    try {
      await login(values.email, values.password)
      navigate('/')
    } catch (e) {
      setError(e.response?.data?.detail || 'Login failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      padding: 24
    }}>
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.4, ease: 'easeOut' }}
      >
        <Card style={{ width: 400, borderRadius: 16, boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
          <Space direction="vertical" size="large" style={{ width: '100%' }}>
            <div style={{ textAlign: 'center' }}>
              <CloudServerOutlined style={{ fontSize: 48, color: '#2563EB', marginBottom: 8 }} />
              <Title level={3} style={{ margin: 0 }}>CloudCRM</Title>
              <Text type="secondary">Sales Intelligence Platform</Text>
            </div>

            {error && <Alert message={error} type="error" showIcon />}

            <Form onFinish={onFinish} layout="vertical" initialValues={{ email: 'admin@cloudcrm.dev', password: 'admin123' }}>
              <Form.Item name="email" label="Email" rules={[{ required: true, type: 'email' }]}>
                <Input prefix={<MailOutlined />} placeholder="admin@cloudcrm.dev" size="large" />
              </Form.Item>
              <Form.Item name="password" label="Password" rules={[{ required: true }]}>
                <Input.Password prefix={<LockOutlined />} placeholder="Password" size="large" />
              </Form.Item>
              <Form.Item>
                <Button type="primary" htmlType="submit" loading={loading} block size="large">
                  Sign In
                </Button>
              </Form.Item>
            </Form>

            <Paragraph type="secondary" style={{ textAlign: 'center', fontSize: 12, margin: 0 }}>
              Demo: admin@cloudcrm.dev / admin123
            </Paragraph>
          </Space>
        </Card>
      </motion.div>
    </div>
  )
}

// frontend/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login-card card">
      <div class="login-header">
        <h1 class="logo">CloudCRM</h1>
        <p class="subtitle">Sales Intelligence Platform</p>
      </div>
      <form @submit.prevent="handleLogin" class="login-form">
        <div class="form-group">
          <label for="email">Email</label>
          <input id="email" type="email" v-model="email" class="input" placeholder="admin@cloudcrm.dev" required />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input id="password" type="password" v-model="password" class="input" placeholder="Enter password" required />
        </div>
        <div v-if="error" class="error-msg">{{ error }}</div>
        <button type="submit" class="btn btn-primary btn-full" :disabled="loading">
          {{ loading ? 'Signing in...' : 'Sign in' }}
        </button>
      </form>
      <p class="demo-hint">Demo: admin@cloudcrm.dev / admin123</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const authStore = useAuthStore()
const router = useRouter()
const email = ref('admin@cloudcrm.dev')
const password = ref('admin123')
const error = ref('')
const loading = ref(false)

async function handleLogin() {
  loading.value = true
  error.value = ''
  try {
    await authStore.login(email.value, password.value)
    router.push('/')
  } catch (e) {
    error.value = e.response?.data?.detail || 'Login failed'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-page {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  background: var(--background);
}

.login-card {
  width: 100%;
  max-width: 400px;
  padding: 2.5rem;
}

.login-header {
  text-align: center;
  margin-bottom: 2rem;
}

.logo {
  font-size: 1.75rem;
  color: var(--primary);
}

.subtitle {
  color: var(--muted);
  font-size: 0.875rem;
  margin-top: 0.25rem;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
}

.form-group label {
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--foreground);
}

.error-msg {
  background: #fce4ec;
  color: var(--destructive);
  padding: 0.5rem 0.75rem;
  border-radius: 6px;
  font-size: 0.8125rem;
}

.btn-full {
  width: 100%;
  justify-content: center;
  padding: 0.75rem;
}

.demo-hint {
  text-align: center;
  margin-top: 1.5rem;
  font-size: 0.75rem;
  color: var(--muted);
}
</style>
